# Generated by Django 4.0.4 on 2022-05-25 10:09

from django.db import migrations, models
import lunch.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=lunch.models.get_file_path)),
                ('description', models.CharField(max_length=250)),
                ('og_price', models.FloatField()),
                ('sell_price', models.FloatField()),
                ('tag', models.CharField(max_length=150)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
